spring.application.name=spring-ai-ali
spring.ai.close.ai.openai-api-key = sk-CmjMbzjAytDCRI91540fYeGJE8hGq1GFw1uXv5ydE3zSpKXE
spring.ai.close.ai.openai-base-url = https://api.openai-proxy.org
spring.ai.close.ai.dashScopeApiKey = sk-e035855cc7924a7f9c457b721d296956